### ISSUE TITLE
META: Enhance maintenance functionality

### ISSUE THREAD

**Issue by arborrow** [arborrow/montserrat#383]
Create tables for equipment, tasks and work order jobs that can be assigned to staff. Equipment should have a location (building) and a vendor including date of purchase, value, estimated lifetime in years before needing to be replaced, etc. Preventative maintenance tasks should be assigned and scheduled into work order jobs for the maintenance staff. Tasks could also include housekeeping tasks or standard maintenance. Ideally, any work performed will be based on a work order so that a history of work done on equipment or in locations can be documented. Tasks should have an estimated amount of manhours needed to complete the job so that estimated staffing and cost of maintenance can be determined.

**Comment by arborrow** [comment]
Develop CRUD for asset_types

- [ ] Database migration
- [ ] Controller 
- [ ] Blades/Resource views
- [ ] Routes
- [ ] Store and Update Requests/Validation
- [ ] Database factory
- [ ] Database seeder 
- [ ] Create permissions (PermissionSeeder)
- [ ] Controller unit tests
- [ ] Request unit tests

**Comment by arborrow** [comment]
Develop CRUD for units of measurement (uom)
Develop CRUD for asset_types

- [ ] Database migration
- [ ] Controller 
- [ ] Blades/Resource views
- [ ] Routes
- [ ] Store and Update Requests/Validation
- [ ] Database factory
- [ ] Database seeder 
- [ ] Create permissions (PermissionSeeder)
- [ ] Controller unit tests
- [ ] Request unit tests
- [ ] Unit tests passing

**Comment by arborrow** [comment]
Develop CRUD for locations

- [ ] Database migration
- [ ] Controller 
- [ ] Blades/Resource views
- [ ] Routes
- [ ] Store and Update Requests/Validation
- [ ] Database factory
- [ ] Database seeder 
- [ ] Create permissions (PermissionSeeder)
- [ ] Controller unit tests
- [ ] Request unit tests
- [ ] Unit tests passing

**Comment by arborrow** [comment]
Develop CRUD for departments

- [ ] Database migration
- [ ] Model
- [ ] Controller 
- [ ] Blades/Resource views
- [ ] Routes
- [ ] Store and Update Requests/Validation
- [ ] Database factory
- [ ] Database seeder 
- [ ] Create permissions (PermissionSeeder)
- [ ] Controller unit tests
- [ ] Request unit tests
- [ ] Unit tests passing

**Comment by arborrow** [comment]
Create asset files
- [ ] Picture
- [ ] Attachments (allow pdfs for manuals and images for issues)
- [ ] Notes (types of notes?)
- [ ] URLs (common URLs, support, parts, drivers, firmware, etc.)

**Comment by arborrow** [comment]
Develop CRUD for websites

- [ ] Database migration
- [ ] Model
- [ ] Controller 
- [ ] Blades/Resource views
- [ ] Routes
- [ ] Store and Update Requests/Validation
- [ ] Database factory
- [ ] Database seeder 
- [ ] Create permissions (PermissionSeeder)
- [ ] Controller unit tests
- [ ] Request unit tests
- [ ] Unit tests passing

**Comment by arborrow** [comment]
Checklist for deployment
- [ ] Git pull
- [ ] Composer and yarn install
- [ ] Drop migrations table
- [ ] Import fresh migrations table from dev (homestead)
- [ ] Delete 2019+ migration records
- [ ] Run art migrate
- [ ] Seeds for AssetType, Uom, Department, AssetPerms, WebsitePerms
- [ ] Replace locations table with polancocurrent export
- [ ] Add new rooms
